language: java
jdk: oraclejdk8
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org
before_script:
  - sleep 15
  - mongo centromere-test --eval 'db.addUser("centromere", "centromere");'
script:
  - cd centromere-parent
  - mvn -U clean test
notifications:
  email:
    recipients:
      - willoemler@gmail.com
    on_success: change
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)
