language: java
jdk: oraclejdk8
services:
  - mongodb
before_script:
  - sleep 15
  - mongo centromere-test --eval 'db.addUser("centromere", "centromere");'
script:
  - cd centromere-parent
  - mvn -U clean test
notifications:
  email:
    recipients:
      - willoemler@gmail.com
    on_success: change
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)
