codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "0...100"

  #status:
  #  project:
  #    default:
  #      target: auto

  #  patch:
  #    default:
  #      target: auto
        
  ignore:
    - centromere-core/src/main/java/com/blueprint/centromere/core/commons/models/*
    - centromere-core/src/main/java/com/blueprint/centromere/core/commons/repositories/*
    - centromere-core/src/main/java/com/blueprint/centromere/core/commons/support/*
    - centromere-core/src/main/java/com/blueprint/centromere/core/model/*

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
